### ISSUE TITLE
Hint arrow interferes with vanilla ones in other locations

### ISSUE THREAD

**Issue by thebinaryeagle** [andmcadams/dk-lights#1]
Writing this on behalf of someone else in the #support channel on the RL discord (RobLFC#0200); they noticed their mole locator arrow was not working and through trial and error turning plugins off/on, discovered it was this one causing the issue. A similar problem used to happen with one of the mahogany homes plugins.

**Comment by andmcadams** [comment]
Alright, I'll look into this. I would guess that it's because it attempts to clear the arrow before it attempts to redraw one on the nearest light. If so I can probably just use a check to make sure the player is in Dorgesh-Kaan. Thanks for letting me know!

**Comment by andmcadams** [comment]
Fixed in #2. Should be fixed once my PR to plugin hub is merged. If the problem persists after that please let me know.
